from master_pack_builder import build_pack

items = [
    {
        "filename": "BEH-000007_exploratory_behavior.yml",
        "id": "BEH-000007",
        "knowledge_type": "behavior_pattern",
        "name_ja": "探索行動",
        "name_en": "Exploratory Behavior",
        "category": "Behavior Patterns",
        "attribute": "Behavior",
        "definition_ja": "未知の選択肢、領域、情報、方法を試しながら理解を広げる行動傾向。",
        "tags": ["CAT:行動", "CAT:探索", "ATTR:行動パターン"],
        "parent": ["行動パターン"],
        "related": ["好奇心", "開放性", "情報探索", "試行錯誤"],
        "observable_data": ["探索範囲", "未選択項目選択率", "新規選択率", "寄り道率"],
        "signal_candidates": ["未知の選択肢を試す", "効率より情報収集を優先する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["自由度", "時間制限", "報酬", "経験"],
        "evidence": "プレイヤーモデリング・UX研究・学習研究で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000008_trial_and_error.yml",
        "id": "BEH-000008",
        "knowledge_type": "behavior_pattern",
        "name_ja": "試行錯誤",
        "name_en": "Trial and Error",
        "category": "Behavior Patterns",
        "attribute": "Behavior",
        "definition_ja": "複数の行動を試し、結果から修正しながら解決へ近づく行動パターン。",
        "tags": ["CAT:行動", "CAT:学習", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["フィードバック学習", "問題解決", "適応力"],
        "observable_data": ["試行回数", "失敗後変更率", "改善率", "再挑戦率"],
        "signal_candidates": ["失敗後に別方法を試す", "反復ごとに成績が改善する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["フィードバック有無", "失敗コスト", "時間制限", "経験"],
        "evidence": "学習心理学・行動分析学・ゲーム研究で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000009_persistence.yml",
        "id": "BEH-000009",
        "knowledge_type": "behavior_pattern",
        "name_ja": "粘り強さ",
        "name_en": "Persistence",
        "category": "Behavior Patterns",
        "attribute": "Behavior",
        "definition_ja": "困難や失敗があっても行動を継続し、目標達成を試みる行動傾向。",
        "tags": ["CAT:行動", "CAT:自己管理", "ATTR:行動パターン"],
        "parent": ["継続行動"],
        "related": ["継続力", "レジリエンス", "達成動機"],
        "observable_data": ["再挑戦率", "離脱率", "継続時間", "失敗後再開時間"],
        "signal_candidates": ["失敗後も続ける", "難易度が上がっても離脱しにくい"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["疲労", "報酬", "成功体験", "課題難易度"],
        "evidence": "教育心理学・非認知能力研究・組織心理学で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000010_procrastination.yml",
        "id": "BEH-000010",
        "knowledge_type": "behavior_pattern",
        "name_ja": "先延ばし",
        "name_en": "Procrastination",
        "category": "Behavior Patterns",
        "attribute": "Behavior",
        "definition_ja": "必要な行動や課題開始を遅らせる行動傾向。",
        "tags": ["CAT:行動", "CAT:自己管理", "ATTR:行動パターン"],
        "parent": ["課題開始"],
        "related": ["課題開始", "時間管理", "不安傾向", "自己規律"],
        "observable_data": ["開始遅延", "期限直前開始率", "未着手率", "持ち越し回数"],
        "signal_candidates": ["開始までに時間がかかる", "期限直前に作業が集中する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["不安", "課題難易度", "疲労", "報酬", "時間制限"],
        "evidence": "自己制御研究・教育心理学・ADHD関連評価で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000011_optimization_behavior.yml",
        "id": "BEH-000011",
        "knowledge_type": "behavior_pattern",
        "name_ja": "最適化行動",
        "name_en": "Optimization Behavior",
        "category": "Behavior Patterns",
        "attribute": "Behavior",
        "definition_ja": "成果、効率、資源配分、手順を改善し、より良い方法へ調整する行動傾向。",
        "tags": ["CAT:行動", "CAT:問題解決", "ATTR:行動パターン"],
        "parent": ["改善行動"],
        "related": ["改善", "効率志向", "問題解決", "計画性"],
        "observable_data": ["手順改善回数", "資源配分変更", "効率改善率", "再設計行動"],
        "signal_candidates": ["より効率的な方法へ変更する", "成果を見て手順を調整する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["経験", "フィードバック", "時間制限", "報酬"],
        "evidence": "UX研究・ゲーム研究・問題解決研究で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000012_safety_seeking.yml",
        "id": "BEH-000012",
        "knowledge_type": "behavior_pattern",
        "name_ja": "安全策選択",
        "name_en": "Safety Seeking",
        "category": "Behavior Patterns",
        "attribute": "Behavior",
        "definition_ja": "損失や失敗の可能性を抑えるため、安全な選択肢を選びやすい行動傾向。",
        "tags": ["CAT:行動", "CAT:意思決定", "ATTR:行動パターン"],
        "parent": ["意思決定行動"],
        "related": ["安全志向", "損失回避", "リスク回避"],
        "observable_data": ["安全選択率", "保険行動", "余裕資源確保", "撤退選択"],
        "signal_candidates": ["リスクが低い選択を優先する", "余裕を持った資源配分をする"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["損失経験", "時間制限", "報酬条件", "ストレス"],
        "evidence": "行動経済学・意思決定研究・安全行動研究で使用",
        "status": "active"
    }
]

build_pack(
    output_path="data/master_packs/vol3_behavior_part2_behavior_patterns.json",
    output_dir="vol3_behavior/behavior_patterns",
    index_filename="behavior_patterns_index.yml",
    index_name_ja="行動パターン",
    category="Behavior Patterns",
    items=items,
    notes=[
        "行動パターンは能力や性格とは統合しない",
        "観測データとSignal候補を中心に管理する",
        "アプリ種別タグは付けない"
    ]
)