from master_pack_builder import build_pack

items = [
    {
        "filename": "BEH-000021_feedback_learning.yml",
        "id": "BEH-000021",
        "knowledge_type": "behavior_pattern",
        "name_ja": "フィードバック学習",
        "name_en": "Feedback Learning",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "結果や評価を手がかりにして、次の行動を修正・改善する学習行動。",
        "tags": ["CAT:学習", "CAT:行動", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["試行錯誤", "エラー修正", "改善行動"],
        "observable_data": ["失敗後変更率", "改善率", "再挑戦率", "フィードバック確認回数"],
        "signal_candidates": ["結果を見て次の行動を変える", "失敗後に成績が改善する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["フィードバック明確性", "疲労", "経験", "報酬"],
        "evidence": "学習心理学・教育工学・行動科学で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000022_experiential_learning.yml",
        "id": "BEH-000022",
        "knowledge_type": "behavior_pattern",
        "name_ja": "経験学習",
        "name_en": "Experiential Learning",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "直接の体験や実践を通じて理解や行動を改善していく学習行動。",
        "tags": ["CAT:学習", "CAT:行動", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["試行錯誤", "習熟", "転移学習"],
        "observable_data": ["試行回数", "経験後改善率", "再挑戦率", "習熟速度"],
        "signal_candidates": ["説明より実践後に改善する", "繰り返すほど行動が安定する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["経験量", "課題難易度", "フィードバック", "疲労"],
        "evidence": "教育心理学・学習科学で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000023_rule_learning.yml",
        "id": "BEH-000023",
        "knowledge_type": "behavior_pattern",
        "name_ja": "ルール学習",
        "name_en": "Rule Learning",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "課題や環境に存在する規則性を理解し、行動に反映する学習行動。",
        "tags": ["CAT:学習", "CAT:推論", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["帰納推論", "パターン学習", "認知の柔軟性"],
        "observable_data": ["ルール発見率", "ルール適用率", "ルール変更後ミス率", "習得試行数"],
        "signal_candidates": ["少ない試行で規則を見つける", "ルール変更後に行動を修正する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["ルール複雑性", "フィードバック", "注意", "経験"],
        "evidence": "認知心理学・学習研究で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000024_pattern_learning.yml",
        "id": "BEH-000024",
        "knowledge_type": "behavior_pattern",
        "name_ja": "パターン学習",
        "name_en": "Pattern Learning",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "反復して現れる構造、順序、規則、配置などを学習する行動。",
        "tags": ["CAT:学習", "CAT:認知", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["パターン認識", "帰納推論", "手続き記憶"],
        "observable_data": ["パターン発見率", "系列予測率", "反復後改善率", "誤反応減少"],
        "signal_candidates": ["繰り返し構造を予測する", "反復後にミスが減る"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["反復回数", "注意", "疲労", "パターン複雑性"],
        "evidence": "認知心理学・技能学習研究で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000025_transfer_learning.yml",
        "id": "BEH-000025",
        "knowledge_type": "behavior_pattern",
        "name_ja": "転移学習",
        "name_en": "Transfer Learning",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "ある課題や経験で得た知識・方略を、別の課題や状況へ応用する学習行動。",
        "tags": ["CAT:学習", "CAT:応用", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["類推", "応用力", "経験学習"],
        "observable_data": ["新課題適応率", "既知方略利用率", "応用成功率", "初見課題改善率"],
        "signal_candidates": ["過去の方法を別課題へ応用する", "似た課題で素早く適応する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["課題類似性", "経験", "抽象化能力", "疲労"],
        "evidence": "教育心理学・学習科学で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000026_improvement_behavior.yml",
        "id": "BEH-000026",
        "knowledge_type": "behavior_pattern",
        "name_ja": "改善行動",
        "name_en": "Improvement Behavior",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "結果や課題を踏まえて、行動・手順・判断をより良くしようとする行動傾向。",
        "tags": ["CAT:学習", "CAT:改善", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["最適化行動", "自己改善", "フィードバック学習"],
        "observable_data": ["改善率", "手順変更回数", "再設計行動", "失敗後変更率"],
        "signal_candidates": ["結果を見て手順を変える", "効率や成果を上げるために調整する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["フィードバック", "経験", "報酬", "時間制限"],
        "evidence": "学習科学・UX研究・問題解決研究で使用",
        "status": "active"
    },
    {
        "filename": "BEH-000027_error_correction.yml",
        "id": "BEH-000027",
        "knowledge_type": "behavior_pattern",
        "name_ja": "エラー修正",
        "name_en": "Error Correction",
        "category": "Learning Behavior",
        "attribute": "Behavior",
        "definition_ja": "ミスや不一致を検出し、原因を修正して行動を改善する行動。",
        "tags": ["CAT:学習", "CAT:エラー", "ATTR:行動パターン"],
        "parent": ["学習行動"],
        "related": ["自己モニタリング", "エラー検出", "改善行動"],
        "observable_data": ["ミス後修正率", "同一ミス再発率", "修正時間", "確認回数"],
        "signal_candidates": ["ミス後すぐに修正する", "同じミスを繰り返す", "原因を確認してから再実行する"],
        "device_level": "スマホ・PCのみ推定可能",
        "modifiers": ["フィードバック明確性", "疲労", "注意", "ストレス"],
        "evidence": "実行機能研究・学習研究・HCIで使用",
        "status": "active"
    }
]

build_pack(
    output_path="data/master_packs/vol3_behavior_part4_learning_behavior.json",
    output_dir="vol3_behavior/learning_behavior",
    index_filename="learning_behavior_index.yml",
    index_name_ja="学習行動",
    category="Learning Behavior",
    items=items,
    notes=[
        "学習行動は能力そのものとは統合しない",
        "観測データとSignal候補を中心に管理する",
        "アプリ種別タグは付けない"
    ]
)