"""Build Vol35-Vol41 traditional divination reference master packs."""

from __future__ import annotations

from build_divination_expansion import build_pack


def named(values, template):
    return [
        (slug, ja, en, template.format(name=ja))
        for slug, ja, en in values
    ]


JYOTISHA_SECTIONS = [
    ("Foundations", "基礎", [
        ("jyotisha", "ジョーティシャ", "Jyotisha", "インドの天文・暦・占星に関わる歴史的知識領域"),
        ("jataka", "ジャータカ", "Jataka", "出生図を対象とするインド占星術の領域"),
        ("sidereal_framework", "恒星黄道方式", "Sidereal Framework", "恒星基準の黄道を採用する方式"),
        ("ayanamsha", "アヤナーンシャ", "Ayanamsha", "歳差にもとづく黄道基点差の採用値"),
        ("lagna", "ラグナ", "Lagna", "出生地点で東の地平線に昇る黄道上の点"),
        ("rashi", "ラーシ", "Rashi", "黄道を十二のサインへ区分する分類"),
        ("graha", "グラハ", "Graha", "出生図で象徴機能を担う九つの感受主体"),
        ("bhava", "バーヴァ", "Bhava", "出生図を十二の生活領域へ区分する枠組み"),
        ("nakshatra", "ナクシャトラ", "Nakshatra", "黄道を二十七の月宿へ区分する体系"),
        ("school_declaration", "方式宣言", "Method Declaration", "アヤナーンシャ・ハウス・ダシャー等の方式を明示すること"),
    ]),
    ("Navagraha", "九曜", named([
        ("surya", "スーリヤ・太陽", "Surya"), ("chandra", "チャンドラ・月", "Chandra"),
        ("mangala", "マンガラ・火星", "Mangala"), ("budha", "ブダ・水星", "Budha"),
        ("guru", "グル・木星", "Guru"), ("shukra", "シュクラ・金星", "Shukra"),
        ("shani", "シャニ・土星", "Shani"), ("rahu", "ラーフ", "Rahu"),
        ("ketu", "ケートゥ", "Ketu"),
    ], "九曜の{name}に割り当てられる伝統的象徴機能")),
    ("Twelve Rashis", "十二ラーシ", named([
        ("mesha", "メーシャ", "Mesha"), ("vrishabha", "ヴリシャバ", "Vrishabha"),
        ("mithuna", "ミトゥナ", "Mithuna"), ("karka", "カルカ", "Karka"),
        ("simha", "シンハ", "Simha"), ("kanya", "カニヤー", "Kanya"),
        ("tula", "トゥラー", "Tula"), ("vrishchika", "ヴリシュチカ", "Vrishchika"),
        ("dhanu", "ダヌ", "Dhanu"), ("makara", "マカラ", "Makara"),
        ("kumbha", "クンバ", "Kumbha"), ("mina", "ミーナ", "Mina"),
    ], "十二ラーシの{name}に割り当てられる支配星・元素・性質などの対応")),
    ("Twelve Bhavas", "十二バーヴァ", named([
        ("first_bhava", "第1バーヴァ", "First Bhava"), ("second_bhava", "第2バーヴァ", "Second Bhava"),
        ("third_bhava", "第3バーヴァ", "Third Bhava"), ("fourth_bhava", "第4バーヴァ", "Fourth Bhava"),
        ("fifth_bhava", "第5バーヴァ", "Fifth Bhava"), ("sixth_bhava", "第6バーヴァ", "Sixth Bhava"),
        ("seventh_bhava", "第7バーヴァ", "Seventh Bhava"), ("eighth_bhava", "第8バーヴァ", "Eighth Bhava"),
        ("ninth_bhava", "第9バーヴァ", "Ninth Bhava"), ("tenth_bhava", "第10バーヴァ", "Tenth Bhava"),
        ("eleventh_bhava", "第11バーヴァ", "Eleventh Bhava"), ("twelfth_bhava", "第12バーヴァ", "Twelfth Bhava"),
    ], "{name}に割り当てられる伝統的な生活領域")),
    ("Nakshatras", "二十七宿", named([
        ("ashwini", "アシュヴィニー", "Ashwini"), ("bharani", "バラニー", "Bharani"),
        ("krittika", "クリッティカー", "Krittika"), ("rohini", "ローヒニー", "Rohini"),
        ("mrigashirsha", "ムリガシーラ", "Mrigashirsha"), ("ardra", "アールドラー", "Ardra"),
        ("punarvasu", "プナルヴァス", "Punarvasu"), ("pushya", "プシャ", "Pushya"),
        ("ashlesha", "アーシュレーシャー", "Ashlesha"), ("magha", "マガー", "Magha"),
        ("purva_phalguni", "プールヴァ・パールグニー", "Purva Phalguni"), ("uttara_phalguni", "ウッタラ・パールグニー", "Uttara Phalguni"),
        ("hasta", "ハスタ", "Hasta"), ("chitra", "チトラー", "Chitra"),
        ("swati", "スヴァーティー", "Swati"), ("vishakha", "ヴィシャーカー", "Vishakha"),
        ("anuradha", "アヌラーダー", "Anuradha"), ("jyeshtha", "ジェーシュター", "Jyeshtha"),
        ("mula", "ムーラ", "Mula"), ("purva_ashadha", "プールヴァ・アーシャーダー", "Purva Ashadha"),
        ("uttara_ashadha", "ウッタラ・アーシャーダー", "Uttara Ashadha"), ("shravana", "シュラヴァナ", "Shravana"),
        ("dhanishtha", "ダニシュター", "Dhanishtha"), ("shatabhisha", "シャタビシャー", "Shatabhisha"),
        ("purva_bhadrapada", "プールヴァ・バードラパダー", "Purva Bhadrapada"), ("uttara_bhadrapada", "ウッタラ・バードラパダー", "Uttara Bhadrapada"),
        ("revati", "レーヴァティー", "Revati"),
    ], "月宿{name}に割り当てられる支配星・象徴・区分")),
    ("Dignity and Relations", "品位と関係", [
        ("own_sign", "自室", "Own Sign", "グラハが支配ラーシに位置する状態"),
        ("exaltation", "高揚", "Exaltation", "グラハが高揚するとされるラーシ上の状態"),
        ("debilitation", "減衰", "Debilitation", "グラハが減衰するとされるラーシ上の状態"),
        ("moolatrikona", "ムーラトリコーナ", "Moolatrikona", "グラハの基盤的領域とされる度数帯"),
        ("natural_friendship", "自然的友好", "Natural Friendship", "グラハ間の恒常的な友好・中立・敵対分類"),
        ("temporary_friendship", "一時的友好", "Temporary Friendship", "出生図上の位置関係から求める一時的関係"),
        ("graha_aspect", "グラハ・ドリシュティ", "Graha Drishti", "グラハごとの伝統的アスペクト規則"),
        ("rashi_aspect", "ラーシ・ドリシュティ", "Rashi Drishti", "ラーシ間の視線関係を用いる流派規則"),
        ("shadbala", "シャドバラ", "Shadbala", "複数要素からグラハの象徴的強度を整理する方式"),
        ("varga_dignity", "分割図品位", "Varga Dignity", "複数の分割図における配置を合わせて扱うこと"),
    ]),
    ("Timing and Techniques", "時期と技法", [
        ("vimshottari_dasha", "ヴィムショッタリ・ダシャー", "Vimshottari Dasha", "出生月宿から惑星期を配列する時期技法"),
        ("dasha_balance", "ダシャー残存期間", "Dasha Balance", "出生時点で残る最初の惑星期を計算すること"),
        ("antardasha", "アンタルダシャー", "Antardasha", "主要惑星期を下位期間へ分割すること"),
        ("gochara", "ゴーチャラ", "Gochara", "現在のグラハ配置を出生図との関係で読む技法"),
        ("navamsha", "ナヴァーンシャ", "Navamsha", "黄道を九分割して作る代表的な分割図"),
        ("divisional_charts", "分割図", "Divisional Charts", "ラーシを細分して特定テーマを読む伝統的技法群"),
        ("yoga", "ヨーガ", "Yoga", "複数グラハ・支配・ハウス関係からなる組合せ"),
        ("muhurta", "ムフールタ", "Muhurta", "開始時刻を選ぶインド占星術の領域"),
        ("prashna", "プラシュナ", "Prashna", "質問時点の図を用いる占星術領域"),
        ("chart_synthesis", "出生図統合", "Chart Synthesis", "ラーシ・バーヴァ・グラハ・宿・時期を全体で扱うこと"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("tradition_label", "伝統表示", "Tradition Label", "ジョーティシャの伝統的解釈であることを表示すること"),
        ("ayanamsha_disclosure", "アヤナーンシャ表示", "Ayanamsha Disclosure", "採用値の違いを計算結果に表示すること"),
        ("birth_time_uncertainty", "出生時刻不確実性", "Birth-Time Uncertainty", "出生時刻誤差がラグナや分割図へ与える影響を示すこと"),
        ("school_variation", "流派差", "School Variation", "パラーシャラ・ジャイミニ等の規則を混同しないこと"),
        ("no_caste_inference", "身分推定禁止", "No Caste Inference", "出生図からカースト・宗教・民族等を推定しないこと"),
        ("no_health_diagnosis", "健康診断禁止", "No Health Diagnosis", "配置から疾患・寿命・妊娠等を診断しないこと"),
        ("no_fatalism", "宿命論回避", "Avoid Fatalism", "カルマやダシャーを不可避の運命として表示しないこと"),
        ("no_ability_ranking", "能力序列化禁止", "No Ability Ranking", "配置から知能・価値・適性を序列化しないこと"),
        ("high_impact_exclusion", "高影響利用禁止", "High-Impact Exclusion", "雇用・教育・保険・信用等に利用しないこと"),
        ("reflective_use", "内省用途", "Reflective Use", "結果を本人が選択・修正できる内省材料として示すこと"),
    ]),
]


ZWD_SECTIONS = [
    ("Foundations", "基礎", [
        ("zi_wei_dou_shu", "紫微斗数", "Zi Wei Dou Shu", "出生情報から十二宮へ星曜を配置する中国占術体系"),
        ("lunar_calendar_input", "太陰太陽暦入力", "Lunisolar Calendar Input", "出生年月日を採用暦へ変換して用いること"),
        ("birth_hour_branch", "出生時支", "Birth Hour Branch", "出生時刻を十二支の時刻帯へ割り当てること"),
        ("chart_grid", "命盤十二宮", "Twelve-Palace Chart", "十二の宮位を地支上へ配置する命盤構造"),
        ("life_palace_anchor", "命宮起点", "Life Palace Anchor", "出生月と時刻から命宮位置を定めること"),
        ("body_palace", "身宮", "Body Palace", "命宮とは別に配置される伝統的な補助宮位"),
        ("star_placement_rules", "安星法", "Star Placement Rules", "出生情報と表にもとづき星曜を配置する規則"),
        ("virtual_stars", "虚星体系", "Virtual Star System", "天体の実位置ではなく計算上の星名を用いること"),
        ("school_lineage", "流派系譜", "School Lineage", "三合派・飛星派等の解釈規則を区別すること"),
        ("calculation_trace", "排盤追跡", "Chart Calculation Trace", "暦変換から星曜配置までを再現可能にすること"),
    ]),
    ("Twelve Palaces", "十二宮", named([
        ("life_palace", "命宮", "Life Palace"), ("siblings_palace", "兄弟宮", "Siblings Palace"),
        ("spouse_palace", "夫妻宮", "Spouse Palace"), ("children_palace", "子女宮", "Children Palace"),
        ("wealth_palace", "財帛宮", "Wealth Palace"), ("health_palace", "疾厄宮", "Health Palace"),
        ("travel_palace", "遷移宮", "Travel Palace"), ("friends_palace", "交友宮", "Friends Palace"),
        ("career_palace", "官禄宮", "Career Palace"), ("property_palace", "田宅宮", "Property Palace"),
        ("fortune_palace", "福徳宮", "Fortune Palace"), ("parents_palace", "父母宮", "Parents Palace"),
    ], "十二宮の{name}に割り当てられる伝統的テーマ領域")),
    ("Fourteen Major Stars", "十四主星", named([
        ("ziwei", "紫微", "Zi Wei"), ("tianji", "天機", "Tian Ji"),
        ("taiyang", "太陽", "Tai Yang"), ("wuqu", "武曲", "Wu Qu"),
        ("tiantong", "天同", "Tian Tong"), ("lianzhen", "廉貞", "Lian Zhen"),
        ("tianfu", "天府", "Tian Fu"), ("taiyin", "太陰", "Tai Yin"),
        ("tanlang", "貪狼", "Tan Lang"), ("jumen", "巨門", "Ju Men"),
        ("tianxiang", "天相", "Tian Xiang"), ("tianliang", "天梁", "Tian Liang"),
        ("qisha", "七殺", "Qi Sha"), ("pojun", "破軍", "Po Jun"),
    ], "十四主星の{name}に割り当てられる伝統的象徴機能")),
    ("Auxiliary Stars", "補助星曜", named([
        ("zuofu", "左輔", "Zuo Fu"), ("youbi", "右弼", "You Bi"),
        ("wenchang", "文昌", "Wen Chang"), ("wenqu", "文曲", "Wen Qu"),
        ("tiankui", "天魁", "Tian Kui"), ("tianyue", "天鉞", "Tian Yue"),
        ("lucun", "禄存", "Lu Cun"), ("tianma", "天馬", "Tian Ma"),
        ("qingyang", "擎羊", "Qing Yang"), ("tuoluo", "陀羅", "Tuo Luo"),
        ("huoxing", "火星", "Huo Xing"), ("lingxing", "鈴星", "Ling Xing"),
        ("dikong", "地空", "Di Kong"), ("dijie", "地劫", "Di Jie"),
        ("hongluan", "紅鸞", "Hong Luan"), ("tianxi", "天喜", "Tian Xi"),
        ("tianxing", "天刑", "Tian Xing"), ("tianyao", "天姚", "Tian Yao"),
        ("tianku", "天哭", "Tian Ku"), ("tianxu", "天虚", "Tian Xu"),
    ], "補助星曜{name}に割り当てられる伝統的象徴")),
    ("Four Transformations", "四化", [
        ("hua_lu", "化禄", "Hua Lu", "天干に応じて特定星曜へ付与する禄の変化"),
        ("hua_quan", "化権", "Hua Quan", "天干に応じて特定星曜へ付与する権の変化"),
        ("hua_ke", "化科", "Hua Ke", "天干に応じて特定星曜へ付与する科の変化"),
        ("hua_ji", "化忌", "Hua Ji", "天干に応じて特定星曜へ付与する忌の変化"),
    ]),
    ("Star Conditions", "星曜条件", [
        ("brightness", "廟旺利陥", "Star Brightness", "宮位に応じた星曜状態を段階表示する流派表"),
        ("five_phase_bureau", "五行局", "Five-Phase Bureau", "命盤から定める五行と局数の分類"),
        ("stem_assignment", "宮干配置", "Palace Stem Assignment", "各宮へ天干を割り当てる規則"),
        ("branch_assignment", "宮支配置", "Palace Branch Assignment", "各宮を地支位置へ割り当てる規則"),
        ("major_minor_priority", "主星補星優先度", "Major-Minor Star Priority", "主星と補助星の解釈優先度を定めること"),
        ("benefic_malefic_label", "吉曜煞曜分類", "Benefic-Malefic Label", "星曜を吉凶へ分類する伝統的ラベル"),
        ("same_palace", "同宮", "Same-Palace Relation", "複数星曜が同じ宮に配置される関係"),
        ("opposite_palace", "対宮", "Opposite-Palace Relation", "向かい合う二宮の関係"),
        ("empty_palace", "空宮", "Empty Palace", "主星が配置されない宮を対宮等から読む規則"),
        ("school_table_version", "星表版管理", "Star-Table Version", "安星表・四化表・明度表の流派版を保持すること"),
    ]),
    ("Palace Relations", "宮位関係", [
        ("san_fang_si_zheng", "三方四正", "Three Directions and Four Positions", "本宮・対宮・三合宮を一単位で読むこと"),
        ("trine_palaces", "三合宮", "Trine Palaces", "地支三合に位置する宮同士の関係"),
        ("adjacent_palaces", "隣宮", "Adjacent Palaces", "隣接する宮位の補助的関係"),
        ("life_body_relation", "命身関係", "Life-Body Relation", "命宮と身宮の配置関係"),
        ("life_fortune_relation", "命福関係", "Life-Fortune Relation", "命宮と福徳宮を対照する読み"),
        ("life_travel_axis", "命遷軸", "Life-Travel Axis", "命宮と遷移宮の対宮関係"),
        ("wealth_fortune_axis", "財福軸", "Wealth-Fortune Axis", "財帛宮と福徳宮等を合わせて読む関係"),
        ("career_spouse_axis", "官夫軸", "Career-Spouse Axis", "官禄宮と夫妻宮等の相互文脈"),
        ("palace_borrowing", "借星安宮", "Borrowed-Star Reading", "空宮を対宮の主星から補助的に読む方法"),
        ("whole_chart_relation", "全盤関係", "Whole-Chart Relation", "一宮だけで断定せず十二宮全体を参照すること"),
    ]),
    ("Timing", "時期運", [
        ("major_limit", "大限", "Major Limit", "十年単位などの期間宮を用いる時期層"),
        ("annual_limit", "流年", "Annual Limit", "年単位の星曜・宮位変化を扱う時期層"),
        ("monthly_limit", "流月", "Monthly Limit", "月単位の変化を扱う時期層"),
        ("daily_limit", "流日", "Daily Limit", "日単位の変化を扱う時期層"),
        ("decade_palace", "大限命宮", "Decade Life Palace", "大限ごとに命宮役割を移すこと"),
        ("annual_transformations", "流年四化", "Annual Transformations", "年干に応じた四化配置"),
        ("flying_transformations", "飛化", "Flying Transformations", "宮干四化の飛入・飛出を読む流派技法"),
        ("timing_overlap", "限運重畳", "Timing Overlap", "本命・大限・流年等を重ねて扱うこと"),
        ("timing_boundary", "時期境界", "Timing Boundary", "旧暦年・節気等の切替規則を明示すること"),
        ("non_deterministic_timing", "非決定論的時期表示", "Non-Deterministic Timing", "時期層を出来事の確定予言として表示しないこと"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("virtual_star_disclosure", "虚星表示", "Virtual-Star Disclosure", "星曜が実天体位置ではないことを明示すること"),
        ("calendar_uncertainty", "暦変換不確実性", "Calendar Uncertainty", "閏月・日界・時支境界の規則を表示すること"),
        ("school_variation", "流派差", "School Variation", "星表・四化・飛星等の流派差を保持すること"),
        ("no_health_diagnosis", "疾厄宮診断禁止", "No Health Diagnosis", "疾厄宮や星曜から病気・寿命を診断しないこと"),
        ("no_relationship_determinism", "関係決定論禁止", "No Relationship Determinism", "夫妻宮等から関係の成否を確定しないこと"),
        ("no_wealth_prediction", "財産保証禁止", "No Wealth Guarantee", "財帛宮等から収入や投資成果を保証しないこと"),
        ("no_ability_ranking", "能力序列化禁止", "No Ability Ranking", "官禄宮等から能力や価値を序列化しないこと"),
        ("no_fatalism", "宿命論回避", "Avoid Fatalism", "煞曜や化忌を不可避の災厄として表示しないこと"),
        ("high_impact_exclusion", "高影響利用禁止", "High-Impact Exclusion", "雇用・教育・保険・信用等に利用しないこと"),
        ("reflective_use", "内省用途", "Reflective Use", "命盤を本人が選択・修正できる会話材料として示すこと"),
    ]),
]


NINE_STARS = [
    ("one_white_water", "一白水星", "One White Water"), ("two_black_earth", "二黒土星", "Two Black Earth"),
    ("three_jade_wood", "三碧木星", "Three Jade Wood"), ("four_green_wood", "四緑木星", "Four Green Wood"),
    ("five_yellow_earth", "五黄土星", "Five Yellow Earth"), ("six_white_metal", "六白金星", "Six White Metal"),
    ("seven_red_metal", "七赤金星", "Seven Red Metal"), ("eight_white_earth", "八白土星", "Eight White Earth"),
    ("nine_purple_fire", "九紫火星", "Nine Purple Fire"),
]


NINE_STAR_SECTIONS = [
    ("Foundations", "基礎", [
        ("nine_star_ki", "九星気学", "Nine Star Ki", "九星・五行・方位・暦周期を組み合わせる日本の占術体系"),
        ("nine_palace_grid", "九宮盤", "Nine-Palace Grid", "中央と八方位へ九星を配置する盤"),
        ("later_heaven_bagua", "後天八卦", "Later-Heaven Bagua", "八方位と八卦を対応づける配列"),
        ("five_phase_assignment", "九星五行配当", "Nine-Star Phase Assignment", "各九星を五行へ配当すること"),
        ("annual_cycle", "年盤", "Annual Chart", "年単位で九星配置が移る盤"),
        ("monthly_cycle", "月盤", "Monthly Chart", "月単位で九星配置が移る盤"),
        ("daily_cycle", "日盤", "Daily Chart", "日単位で九星配置が移る盤"),
        ("hourly_cycle", "時盤", "Hourly Chart", "時刻単位で九星配置を扱う盤"),
        ("school_declaration", "流派宣言", "School Declaration", "節替わり・日盤・傾斜等の採用規則を明示すること"),
        ("calculation_trace", "盤計算追跡", "Chart Calculation Trace", "暦入力から各盤までを再現可能にすること"),
    ]),
    ("Nine Stars", "九星", named(NINE_STARS, "九星の{name}に割り当てられる数・色・五行・宮位の伝統的対応")),
    ("Palaces and Directions", "九宮方位", named([
        ("center_palace", "中宮", "Center Palace"), ("north", "北", "North"),
        ("southwest", "南西", "Southwest"), ("east", "東", "East"),
        ("southeast", "南東", "Southeast"), ("northwest", "北西", "Northwest"),
        ("west", "西", "West"), ("northeast", "北東", "Northeast"),
        ("south", "南", "South"),
    ], "九宮盤の{name}に割り当てられる方位・卦・五行の対応")),
    ("Cycles", "運行周期", [
        ("annual_flight", "年盤遁行", "Annual Flight", "年ごとに中宮星と配置を移す規則"),
        ("monthly_flight", "月盤遁行", "Monthly Flight", "月ごとに九星配置を移す規則"),
        ("daily_flight", "日盤遁行", "Daily Flight", "日ごとに九星配置を移す規則"),
        ("hourly_flight", "時盤遁行", "Hourly Flight", "時刻ごとに九星配置を移す規則"),
        ("yang_flight", "陽遁", "Yang Flight", "九星を順方向へ巡らせる周期方式"),
        ("yin_flight", "陰遁", "Yin Flight", "九星を逆方向へ巡らせる周期方式"),
        ("solar_term_switch", "節替わり", "Solar-Term Switch", "節気を年・月の境界に用いる規則"),
        ("nine_year_cycle", "九年周期", "Nine-Year Cycle", "年盤の九星が巡る周期"),
        ("nine_month_cycle", "九か月周期", "Nine-Month Cycle", "月盤の九星が巡る周期"),
        ("nine_day_cycle", "九日周期", "Nine-Day Cycle", "日盤で九星が巡る基本周期"),
        ("cycle_boundary", "周期境界", "Cycle Boundary", "節入りや陰陽遁切替の境界を明示すること"),
        ("cycle_version", "暦表版管理", "Calendar-Table Version", "採用する万年暦・計算法の版を保持すること"),
    ]),
    ("Personal Stars", "個人星", [
        ("main_star", "本命星", "Main Birth Star", "出生年から求める九星分類"),
        ("month_star", "月命星", "Month Birth Star", "出生月から求める九星分類"),
        ("inclination", "傾斜", "Inclination", "本命星と月命星の配置関係から求める流派分類"),
        ("main_palace", "本命宮", "Main Birth Palace", "本命星が年盤上で位置する宮"),
        ("opposite_main", "本命的殺", "Opposite Main Direction", "本命星の反対宮を扱う伝統的方位概念"),
        ("same_star_relation", "同会", "Same-Star Relation", "本命星と盤の九星が重なる関係"),
        ("phase_relation", "五行関係", "Phase Relation", "本人星と方位星の相生・相剋関係"),
        ("annual_personal_context", "年盤個人文脈", "Annual Personal Context", "本命星と年盤配置を重ねること"),
        ("monthly_personal_context", "月盤個人文脈", "Monthly Personal Context", "本命星・月命星と月盤を重ねること"),
        ("personal_uncertainty", "個人星不確実性", "Personal-Star Uncertainty", "立春・節入り付近の出生で計算差を表示すること"),
    ]),
    ("Directional Concepts", "方位概念", named([
        ("auspicious_direction", "吉方位", "Auspicious Direction"), ("inauspicious_direction", "凶方位", "Inauspicious Direction"),
        ("five_yellow_direction", "五黄殺", "Five Yellow Direction"), ("opposite_five_yellow", "暗剣殺", "Opposite Five Yellow"),
        ("year_breaker", "歳破", "Year Breaker"), ("month_breaker", "月破", "Month Breaker"),
        ("main_star_killing", "本命殺", "Main-Star Killing"), ("opposite_main_star", "本命的殺", "Opposite Main-Star Killing"),
        ("directional_distance", "方位距離", "Directional Distance"), ("directional_boundary", "方位境界", "Directional Boundary"),
        ("departure_point", "出発地点", "Departure Point"), ("destination_point", "目的地点", "Destination Point"),
        ("travel_date", "移動日", "Travel Date"), ("stay_duration", "滞在期間", "Stay Duration"),
        ("sector_overlap", "方位重複", "Sector Overlap"), ("annual_monthly_overlap", "年月盤重合", "Annual-Monthly Overlap"),
        ("compass_bearing", "方位角", "Compass Bearing"), ("map_projection", "地図投影", "Map Projection"),
        ("magnetic_true_north", "磁北・真北差", "Magnetic-True North Difference"), ("direction_uncertainty", "方位不確実性", "Direction Uncertainty"),
    ], "九星気学で{name}を扱う際の伝統的計算・分類概念")),
    ("Calendar Calculation", "暦計算", [
        ("risshun_year_start", "立春年始", "Risshun Year Start", "立春を年盤切替の基準とすること"),
        ("monthly_solar_terms", "節月", "Solar-Term Months", "節入りを月盤切替の基準とすること"),
        ("leap_calendar_handling", "閏処理", "Leap Handling", "暦上の例外や補正を明示すること"),
        ("longitude_time_adjustment", "経度時差補正", "Longitude Time Adjustment", "必要な流派で地方時を考慮すること"),
        ("date_rollover", "日界規則", "Date Rollover", "日盤の切替時刻を明示すること"),
        ("winter_solstice_rule", "冬至規則", "Winter-Solstice Rule", "陰陽遁切替に関する採用規則"),
        ("summer_solstice_rule", "夏至規則", "Summer-Solstice Rule", "陰陽遁切替に関する採用規則"),
        ("calendar_source", "万年暦出典", "Calendar Source", "盤作成に用いた暦資料を記録すること"),
        ("calculation_reproducibility", "計算再現性", "Calculation Reproducibility", "入力と規則から同じ盤を再生成できること"),
        ("boundary_warning", "境界警告", "Boundary Warning", "節入り・日界付近で複数候補を表示すること"),
    ]),
    ("Applications", "応用", [
        ("travel_planning", "移動計画", "Travel Planning", "移動方位を伝統的象徴として検討する用途"),
        ("moving_context", "転居文脈", "Moving Context", "転居方位・時期を文化的参照として扱う用途"),
        ("daily_reflection", "日次内省", "Daily Reflection", "日盤を日々の内省テーマに用いること"),
        ("monthly_reflection", "月次内省", "Monthly Reflection", "月盤を月ごとの内省テーマに用いること"),
        ("annual_reflection", "年次内省", "Annual Reflection", "年盤を年ごとの内省テーマに用いること"),
        ("relationship_prompt", "関係対話", "Relationship Prompt", "個人星の関係を会話の問いに変換すること"),
        ("location_comparison", "地点比較", "Location Comparison", "複数候補地の方位条件を並列表示すること"),
        ("multiple_date_comparison", "日程比較", "Date Comparison", "複数日程の盤を断定せず比較表示すること"),
        ("user_preference", "本人選好", "User Preference", "占術結果より安全・費用・本人希望を優先すること"),
        ("practical_constraints", "現実制約", "Practical Constraints", "交通・天候・健康・法令等を占術より優先すること"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("no_travel_safety_claim", "移動安全保証禁止", "No Travel Safety Claim", "吉凶方位から事故や安全を予測しないこと"),
        ("no_disaster_prediction", "災害予測禁止", "No Disaster Prediction", "方位や盤から災害を予測しないこと"),
        ("no_personality_fixing", "性格固定禁止", "No Personality Fixing", "本命星を固定的人格類型にしないこと"),
        ("calendar_variation", "暦差表示", "Calendar Variation", "盤計算法・境界・暦表の差を表示すること"),
        ("school_variation", "流派差", "School Variation", "気学・方位術等の違いを混同しないこと"),
        ("no_fatalism", "凶方位宿命論回避", "Avoid Directional Fatalism", "凶方位を不可避の災厄として表示しないこと"),
        ("no_financial_decision", "金融判断禁止", "No Financial Decision", "投資・契約判断に方位結果を使用しないこと"),
        ("high_impact_exclusion", "高影響利用禁止", "High-Impact Exclusion", "雇用・教育・保険・信用等に利用しないこと"),
        ("location_privacy", "位置情報保護", "Location Privacy", "住所・移動履歴・目的地の収集を最小化すること"),
        ("reflective_use", "内省用途", "Reflective Use", "方位結果を任意の内省・計画補助として示すこと"),
    ]),
]


SUKUYO_MANSIONS = [
    ("bo", "昴宿", "Bo"), ("hitsu", "畢宿", "Hitsu"), ("shi", "觜宿", "Shi"),
    ("shin", "参宿", "Shin"), ("sei_well", "井宿", "Sei"), ("ki_ghost", "鬼宿", "Ki"),
    ("ryu", "柳宿", "Ryu"), ("sei_star", "星宿", "Sei Star"), ("cho", "張宿", "Cho"),
    ("yoku", "翼宿", "Yoku"), ("shin_chariot", "軫宿", "Shin Chariot"), ("kaku", "角宿", "Kaku"),
    ("ko", "亢宿", "Ko"), ("tei", "氐宿", "Tei"), ("bo_room", "房宿", "Bo Room"),
    ("shin_heart", "心宿", "Shin Heart"), ("bi", "尾宿", "Bi"), ("ki_basket", "箕宿", "Ki Basket"),
    ("to", "斗宿", "To"), ("jo", "女宿", "Jo"), ("kyo", "虚宿", "Kyo"),
    ("ki_danger", "危宿", "Ki Danger"), ("shitsu", "室宿", "Shitsu"), ("heki", "壁宿", "Heki"),
    ("kei", "奎宿", "Kei"), ("ro", "婁宿", "Ro"), ("i", "胃宿", "I"),
]


SUKUYO_SECTIONS = [
    ("Foundations", "基礎", [
        ("sukuyo", "宿曜", "Sukuyo", "月宿・七曜・暦日関係を用いる日本の密教占星術系統"),
        ("sukuyokyo", "宿曜経", "Xiuyao Jing", "宿曜体系の伝来で中心となった漢訳仏教占星文献"),
        ("twenty_seven_mansions", "二十七宿", "Twenty-Seven Mansions", "月の黄道上の位置を二十七宿へ区分する体系"),
        ("twenty_eight_mansions", "二十八宿", "Twenty-Eight Mansions", "牛宿を含む二十八宿体系との違い"),
        ("seven_day_week", "七曜", "Seven Luminaries", "日月五星と曜日を対応づける体系"),
        ("birth_mansion", "本命宿", "Birth Mansion", "生年月日から求める出生時の宿分類"),
        ("daily_mansion", "日運宿", "Daily Mansion", "暦日に割り当てられる宿"),
        ("calendar_method", "宿算出法", "Mansion Calculation Method", "採用暦・基準日・二十七宿配列から宿を求めること"),
        ("transmission_context", "密教伝来文脈", "Esoteric Buddhist Transmission", "インド・中国・日本で変化した歴史的文脈"),
        ("school_declaration", "流派宣言", "School Declaration", "宿配列・暦・相性規則の採用方式を明示すること"),
    ]),
    ("Twenty-Seven Mansions", "二十七宿", named(SUKUYO_MANSIONS, "二十七宿の{name}に割り当てられる伝統的象徴と分類")),
    ("Seven Luminaries", "七曜", named([
        ("sun", "日曜", "Sun"), ("moon", "月曜", "Moon"), ("mars", "火曜", "Mars"),
        ("mercury", "水曜", "Mercury"), ("jupiter", "木曜", "Jupiter"),
        ("venus", "金曜", "Venus"), ("saturn", "土曜", "Saturn"),
    ], "七曜の{name}に割り当てられる曜日・天体の伝統的対応")),
    ("Nine Luminaries", "九曜", named([
        ("sun_luminary", "日曜星", "Sun Luminary"), ("moon_luminary", "月曜星", "Moon Luminary"),
        ("mars_luminary", "火曜星", "Mars Luminary"), ("mercury_luminary", "水曜星", "Mercury Luminary"),
        ("jupiter_luminary", "木曜星", "Jupiter Luminary"), ("venus_luminary", "金曜星", "Venus Luminary"),
        ("saturn_luminary", "土曜星", "Saturn Luminary"), ("rahu", "羅睺", "Rahu"),
        ("ketu", "計都", "Ketu"),
    ], "九曜の{name}に割り当てられる伝統的象徴")),
    ("Mansion Relationships", "宿関係", [
        ("ei_shin", "栄親", "Prosperity-Closeness", "宿間距離から栄・親を組にする伝統的関係分類"),
        ("an_kai", "安壊", "Stability-Destruction", "宿間距離から安・壊を組にする伝統的関係分類"),
        ("sei_ki", "成危", "Achievement-Danger", "宿間距離から成・危を組にする伝統的関係分類"),
        ("gyo_tai", "業胎", "Karma-Womb", "宿間距離から業・胎を組にする伝統的関係分類"),
        ("mei_relation", "命", "Same-Mansion Relation", "同じ本命宿同士の関係分類"),
        ("near_distance", "近距離関係", "Near-Distance Relation", "宿間距離の近区分"),
        ("middle_distance", "中距離関係", "Middle-Distance Relation", "宿間距離の中区分"),
        ("far_distance", "遠距離関係", "Far-Distance Relation", "宿間距離の遠区分"),
        ("directional_pair", "関係方向", "Directional Pair", "二人の宿の順序で関係名が変わること"),
        ("relationship_non_determinism", "関係非決定論", "Relationship Non-Determinism", "宿関係を現実の相性や安全性の確定判定にしないこと"),
    ]),
    ("Calendar Days", "暦日分類", [
        ("auspicious_day", "吉祥日分類", "Auspicious-Day Class", "暦日を伝統上の吉祥分類へ割り当てること"),
        ("inauspicious_day", "注意日分類", "Caution-Day Class", "暦日を伝統上の注意分類へ割り当てること"),
        ("activity_day", "行為別日", "Activity-Specific Day", "特定の行為に関する暦注分類"),
        ("weekday_mansion_relation", "曜宿関係", "Weekday-Mansion Relation", "曜日と宿の組合せを扱うこと"),
        ("lunar_date", "太陰日", "Lunar Date", "月相・太陰暦上の日を参照すること"),
        ("calendar_epoch", "暦元", "Calendar Epoch", "宿配列計算の起点となる基準"),
        ("leap_month", "閏月処理", "Leap-Month Handling", "太陰太陽暦の閏月を扱う規則"),
        ("date_boundary", "日界", "Date Boundary", "一日の切替規則を明示すること"),
        ("historical_calendar", "歴史暦法", "Historical Calendar", "宣明暦など時代ごとの暦法差を扱うこと"),
        ("modern_conversion", "現代暦変換", "Modern Calendar Conversion", "グレゴリオ暦入力から採用宿を求める変換規則"),
    ]),
    ("Techniques", "技法", [
        ("birth_mansion_interpretation", "本命宿解釈", "Birth-Mansion Interpretation", "本命宿を象徴的な内省テーマとして読むこと"),
        ("mansion_distance", "宿間距離", "Mansion Distance", "二宿間の循環距離を計算すること"),
        ("daily_cycle", "宿日循環", "Mansion Daily Cycle", "宿が日ごとに巡る配列"),
        ("monthly_context", "月周期文脈", "Monthly Context", "月の運行と宿を月単位で参照すること"),
        ("seven_luminary_context", "七曜文脈", "Seven-Luminary Context", "曜日・七曜を宿解釈へ重ねること"),
        ("nine_luminary_context", "九曜文脈", "Nine-Luminary Context", "羅睺・計都を含む九曜を参照すること"),
        ("relationship_prompt", "宿関係対話", "Mansion-Relationship Prompt", "宿関係を対人対話の問いへ変換すること"),
        ("date_comparison", "日程比較", "Date Comparison", "複数日程の暦注を並列表示すること"),
        ("calculation_trace", "宿算出追跡", "Mansion Calculation Trace", "入力日から宿・関係までの算出経路を保存すること"),
        ("multiple_method_result", "方式別結果", "Method-Specific Result", "異なる暦法・流派の結果を混ぜず提示すること"),
    ]),
    ("History and Text", "歴史と文献", [
        ("indian_lunar_mansions", "インド月宿系譜", "Indian Lunar-Mansion Lineage", "インドのナクシャトラ体系との歴史的関係"),
        ("chinese_translation", "漢訳宿曜経", "Chinese Translation Tradition", "漢訳文献を介した東アジアへの伝承"),
        ("kukais_transmission", "空海将来伝承", "Kukai Transmission Tradition", "空海による宿曜経将来の歴史的伝承"),
        ("sukuyodo", "宿曜道", "Sukuyodo", "日本で形成された宿曜専門家・実践の歴史"),
        ("calendar_change", "改暦影響", "Calendar-Reform Impact", "暦法変更が宿計算へ与えた影響"),
        ("textual_variants", "文献異本", "Textual Variants", "宿名・配列・規則に見られる文献差"),
        ("modern_sukuyo", "現代宿曜", "Modern Sukuyo", "現代日本で再構成された流派・表示方法"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("historical_label", "歴史体系表示", "Historical-System Label", "密教占星・暦注の歴史的体系であることを表示すること"),
        ("calendar_variation", "暦法差表示", "Calendar Variation", "二十七宿・二十八宿・基準日の違いを表示すること"),
        ("no_relationship_determinism", "相性決定論禁止", "No Relationship Determinism", "栄親・安壊等から関係の成否や危険性を確定しないこと"),
        ("no_health_prediction", "健康予測禁止", "No Health Prediction", "宿や曜から病気・寿命を予測しないこと"),
        ("no_disaster_prediction", "災厄予測禁止", "No Disaster Prediction", "注意日を事故や災害の確定予測にしないこと"),
        ("no_religious_inference", "宗教推定禁止", "No Religious Inference", "利用から本人の信仰・宗教を推定しないこと"),
        ("no_fatalism", "宿命論回避", "Avoid Fatalism", "宿を不可変の運命や人格として表示しないこと"),
        ("high_impact_exclusion", "高影響利用禁止", "High-Impact Exclusion", "雇用・教育・保険・信用等に利用しないこと"),
        ("birth_data_privacy", "出生情報保護", "Birth-Data Privacy", "生年月日と派生宿情報の収集・保持を最小化すること"),
        ("reflective_use", "内省用途", "Reflective Use", "結果を本人が拒否・修正できる内省材料として示すこと"),
    ]),
]


NUMEROLOGY_SECTIONS = [
    ("Foundations", "基礎", [
        ("numerology", "数秘術", "Numerology", "数と人物・出来事へ象徴的関係を与える諸伝統の総称"),
        ("arithmancy", "アリスマンシー", "Arithmancy", "文字や数を用いる西洋の占数術系統"),
        ("number_symbolism", "数象徴", "Number Symbolism", "文化・宗教・思想で数へ意味を対応づけること"),
        ("reduction", "数の還元", "Number Reduction", "複数桁を加算等で基本数へまとめる手続き"),
        ("alphabet_mapping", "文字数値対応", "Alphabet Mapping", "文字体系へ数値を割り当てる規則"),
        ("system_declaration", "方式宣言", "System Declaration", "ピタゴラス式・カルデア式等の方式を明示すること"),
        ("input_normalization", "入力正規化", "Input Normalization", "氏名表記・暦・区切り・記号の扱いを固定すること"),
        ("calculation_trace", "計算追跡", "Calculation Trace", "入力から各数までの計算経路を保存すること"),
        ("cultural_context", "文化文脈", "Cultural Context", "数の象徴が文化・時代・伝統で異なること"),
        ("non_scientific_boundary", "非科学的根拠境界", "Non-Scientific Boundary", "数学的性質と占術的象徴を混同しないこと"),
    ]),
    ("Core Calculations", "主要数", [
        ("life_path", "ライフパス数", "Life Path Number", "生年月日の数字を還元して得る代表的な数"),
        ("birthday_number", "誕生日数", "Birthday Number", "出生した日の日付から得る数"),
        ("expression_number", "表現数", "Expression Number", "氏名全体の文字数値から得る数"),
        ("soul_urge", "ソウル数", "Soul Urge Number", "氏名中の母音に対応する数から得る数"),
        ("personality_number", "パーソナリティ数", "Personality Number", "氏名中の子音に対応する数から得る数"),
        ("maturity_number", "成熟数", "Maturity Number", "複数の主要数を組み合わせて得る数"),
        ("balance_number", "バランス数", "Balance Number", "氏名の頭文字等を用いる流派計算"),
        ("attitude_number", "態度数", "Attitude Number", "誕生月と誕生日を組み合わせる流派計算"),
        ("hidden_passion", "隠れた情熱数", "Hidden Passion Number", "氏名数値の出現頻度から求める流派概念"),
        ("missing_numbers", "欠如数", "Missing Numbers", "氏名数値に現れない数を扱う流派概念"),
    ]),
    ("Single Digits", "基本数", named([
        ("number_one", "数1", "Number One"), ("number_two", "数2", "Number Two"),
        ("number_three", "数3", "Number Three"), ("number_four", "数4", "Number Four"),
        ("number_five", "数5", "Number Five"), ("number_six", "数6", "Number Six"),
        ("number_seven", "数7", "Number Seven"), ("number_eight", "数8", "Number Eight"),
        ("number_nine", "数9", "Number Nine"),
    ], "還元後の基本数{name}に割り当てられる伝統的象徴")),
    ("Special Numbers", "特殊数", [
        ("master_eleven", "マスターナンバー11", "Master Number 11", "還元を止める流派で11へ与える象徴"),
        ("master_twenty_two", "マスターナンバー22", "Master Number 22", "還元を止める流派で22へ与える象徴"),
        ("master_thirty_three", "マスターナンバー33", "Master Number 33", "還元を止める流派で33へ与える象徴"),
        ("karmic_thirteen", "カルマ数13", "Karmic Number 13", "一部流派で13へ与える課題象徴"),
        ("karmic_fourteen", "カルマ数14", "Karmic Number 14", "一部流派で14へ与える課題象徴"),
        ("karmic_sixteen", "カルマ数16", "Karmic Number 16", "一部流派で16へ与える課題象徴"),
        ("karmic_nineteen", "カルマ数19", "Karmic Number 19", "一部流派で19へ与える課題象徴"),
        ("compound_number", "複合数", "Compound Number", "還元前の二桁以上も象徴として保持する方式"),
        ("zero_symbolism", "数0", "Zero Symbolism", "0へ独自の象徴を与える近現代流派"),
        ("special_number_variation", "特殊数流派差", "Special-Number Variation", "特殊数の採用範囲が流派で異なること"),
    ]),
    ("Name Methods", "氏名計算", [
        ("pythagorean_mapping", "ピタゴラス式配当", "Pythagorean Mapping", "ラテン文字を1から9へ循環配当する近現代方式"),
        ("chaldean_mapping", "カルデア式配当", "Chaldean Mapping", "文字へ1から8を中心に配当する方式"),
        ("full_birth_name", "出生時氏名", "Full Birth Name", "出生時の正式氏名を入力とする方式"),
        ("current_name", "現在名", "Current Name", "現在使用する氏名を別入力として扱う方式"),
        ("nickname", "通称", "Nickname", "通称・芸名を別の表記単位として扱う方式"),
        ("vowel_classification", "母音分類", "Vowel Classification", "文字を母音と子音へ分類する規則"),
        ("letter_frequency", "文字数値頻度", "Letter-Number Frequency", "対応数の出現回数を集計すること"),
        ("name_normalization", "氏名表記正規化", "Name Normalization", "大文字小文字・記号・空白・アクセントを扱う規則"),
        ("multilingual_name", "多言語氏名", "Multilingual Name", "異なる文字体系の氏名を一律変換しないこと"),
        ("name_method_disclosure", "氏名方式表示", "Name-Method Disclosure", "採用した文字数値表と氏名版を表示すること"),
    ]),
    ("Date Cycles", "日付周期", [
        ("personal_year", "個人年", "Personal Year", "誕生月日と対象年から求める年周期数"),
        ("personal_month", "個人月", "Personal Month", "個人年と対象月から求める月周期数"),
        ("personal_day", "個人日", "Personal Day", "個人月と対象日から求める日周期数"),
        ("universal_year", "世界年", "Universal Year", "対象年の数字を還元する周期数"),
        ("universal_month", "世界月", "Universal Month", "世界年と月から求める周期数"),
        ("pinnacle_cycle", "頂点周期", "Pinnacle Cycle", "生年月日から複数の人生期間を算出する流派技法"),
        ("challenge_cycle", "課題周期", "Challenge Cycle", "生年月日の数差から期間課題を求める流派技法"),
        ("period_cycle", "期間数", "Period Cycle", "誕生月日年を長期期間へ対応させる技法"),
        ("cycle_boundary", "周期境界", "Cycle Boundary", "誕生日・暦年等の切替方式を明示すること"),
        ("non_predictive_cycle", "非予言的周期表示", "Non-Predictive Cycle", "周期数を出来事の確定予言にしないこと"),
    ]),
    ("Traditions", "方式と伝統", [
        ("western_modern", "近現代西洋数秘術", "Modern Western Numerology", "英語圏で体系化された氏名・生年月日方式群"),
        ("greek_number_symbolism", "ギリシャ数象徴", "Greek Number Symbolism", "古代ギリシャ思想における数象徴の歴史文脈"),
        ("isopsephy", "アイソプセフィー", "Isopsephy", "ギリシャ文字の数値を合計する歴史的方法"),
        ("gematria", "ゲマトリア", "Gematria", "ヘブライ文字等の数値対応を用いる解釈伝統"),
        ("abjad_numerals", "アブジャド数価", "Abjad Numerals", "アラビア文字の歴史的数価体系"),
        ("chinese_number_symbolism", "中国数象徴", "Chinese Number Symbolism", "漢語音・宇宙論・慣習に関わる数象徴"),
        ("japanese_number_symbolism", "日本数象徴", "Japanese Number Symbolism", "語呂・宗教・慣習に関わる日本の数象徴"),
        ("system_non_equivalence", "方式非等価性", "System Non-Equivalence", "異文化の数体系を同一方式として混合しないこと"),
        ("historical_context", "歴史文脈", "Historical Context", "数象徴の時代・言語・宗教的背景を記録すること"),
        ("source_provenance", "出典来歴", "Source Provenance", "配当表・計算法・意味づけの出典を記録すること"),
    ]),
    ("Interpretation", "解釈", [
        ("single_number_prompt", "単数プロンプト", "Single-Number Prompt", "一つの数を内省の問いへ変換すること"),
        ("number_combination", "数の組合せ", "Number Combination", "複数の主要数を関係として読むこと"),
        ("repeated_number", "反復数", "Repeated Number", "複数計算で同じ数が現れることを整理すること"),
        ("contrasting_numbers", "対照数", "Contrasting Numbers", "異なる象徴を矛盾のまま併記すること"),
        ("compound_and_reduced", "複合数と還元数", "Compound and Reduced Numbers", "還元前後の両方を保持すること"),
        ("calculation_confidence", "計算確度", "Calculation Confidence", "入力と方式が確定している度合いを示すこと"),
        ("interpretive_uncertainty", "解釈不確実性", "Interpretive Uncertainty", "象徴の多義性と流派差を表示すること"),
        ("user_resonance", "本人照合", "User Resonance", "本人が当てはまり方を選択・修正できること"),
        ("narrative_generation", "物語生成", "Narrative Generation", "数象徴から複数の物語案を作ること"),
        ("trait_link_boundary", "性格リンク境界", "Trait-Link Boundary", "性格辞書へのリンクを実証的相関とみなさないこと"),
        ("whole_profile", "全体プロファイル", "Whole Profile", "単一の数だけで人物を断定しないこと"),
    ]),
    ("Applications", "応用", [
        ("self_reflection", "自己内省", "Self-Reflection", "数象徴を自己理解の問いに用いること"),
        ("conversation_prompt", "会話プロンプト", "Conversation Prompt", "結果を対話のきっかけに用いること"),
        ("character_creation", "キャラクター作成", "Character Creation", "物語やゲームの人物設定に用いること"),
        ("daily_theme", "日次テーマ", "Daily Theme", "個人日を任意の日次テーマとして示すこと"),
        ("annual_theme", "年次テーマ", "Annual Theme", "個人年を任意の年次テーマとして示すこと"),
        ("name_variant_comparison", "名前版比較", "Name-Variant Comparison", "複数の氏名表記結果を並列表示すること"),
        ("method_comparison", "方式比較", "Method Comparison", "異なる配当方式の結果を混合せず比較すること"),
        ("creative_prompt", "創作プロンプト", "Creative Prompt", "数象徴を文章・デザイン等の創作素材に用いること"),
        ("user_choice", "本人選択", "User Choice", "利用者が採用する方式や解釈を選べること"),
        ("explainable_output", "説明可能出力", "Explainable Output", "入力・計算・還元過程を結果とともに表示すること"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("no_mathematical_claim", "数学的証明との混同禁止", "No Mathematical Validity Claim", "計算手続きの正しさと占術的妥当性を混同しないこと"),
        ("no_personality_fixing", "性格固定禁止", "No Personality Fixing", "数から固定的人格や能力を断定しないこと"),
        ("no_future_certainty", "未来確定禁止", "No Future Certainty", "周期数から出来事を確定予測しないこと"),
        ("no_health_prediction", "健康予測禁止", "No Health Prediction", "数から病気・寿命を推定しないこと"),
        ("no_relationship_determinism", "相性決定論禁止", "No Relationship Determinism", "数の一致から関係の成否を確定しないこと"),
        ("no_financial_decision", "金融判断禁止", "No Financial Decision", "数を投資・契約判断へ使わないこと"),
        ("high_impact_exclusion", "高影響利用禁止", "High-Impact Exclusion", "雇用・教育・保険・信用等に利用しないこと"),
        ("name_privacy", "氏名情報保護", "Name Privacy", "氏名・生年月日の収集と保持を最小化すること"),
        ("cultural_respect", "文化的尊重", "Cultural Respect", "宗教的・文化的数象徴を軽率に普遍化しないこと"),
        ("reflective_use", "内省用途", "Reflective Use", "結果を任意の内省・創作・娯楽として表示すること"),
    ]),
]


NAME_SECTIONS = [
    ("Foundations", "基礎", [
        ("name_divination", "姓名判断", "Name Divination", "氏名の文字・画数・音・意味へ象徴的解釈を与える諸方式"),
        ("onomancy", "オノマンシー", "Onomancy", "名前を用いる占術一般の比較概念"),
        ("written_name", "表記名", "Written Name", "判定対象となる具体的な氏名表記"),
        ("reading_name", "読み名", "Name Reading", "氏名の読み・発音を独立入力として扱うこと"),
        ("family_given_split", "姓・名分割", "Family-Given Name Split", "姓と名の境界を方式ごとに定義すること"),
        ("system_declaration", "方式宣言", "System Declaration", "五格・陰陽配列・音・字義等の採用方式を明示すること"),
        ("dictionary_declaration", "字典宣言", "Character-Dictionary Declaration", "画数計算に用いる字体・字典・旧字体規則を示すこと"),
        ("calculation_trace", "計算追跡", "Calculation Trace", "文字入力から画数・格・解釈までを保存すること"),
        ("cultural_context", "命名文化文脈", "Naming Cultural Context", "時代・言語・地域・家族慣習で名前の意味が異なること"),
        ("non_diagnostic_boundary", "非診断境界", "Non-Diagnostic Boundary", "名前から性格・能力・運命を事実として判定しないこと"),
    ]),
    ("Name Inputs", "氏名入力", [
        ("legal_name", "戸籍名", "Legal Name", "法的氏名を本人同意のもと入力すること"),
        ("birth_name", "出生名", "Birth Name", "出生時の氏名を別版として扱うこと"),
        ("current_name", "現在名", "Current Name", "改姓改名後の現在名を別版として扱うこと"),
        ("professional_name", "芸名・活動名", "Professional Name", "活動上の名称を別版として扱うこと"),
        ("nickname", "通称", "Nickname", "日常の通称を別版として扱うこと"),
        ("kanji_form", "漢字表記", "Kanji Form", "漢字の具体的字体を保持すること"),
        ("kana_form", "かな表記", "Kana Form", "かなによる読み表記を保持すること"),
        ("romanized_form", "ローマ字表記", "Romanized Form", "ローマ字方式を明示して保持すること"),
        ("name_order", "姓名順序", "Name Order", "姓・名の表示順を文化文脈とともに保持すること"),
        ("missing_reading", "読み不明", "Missing Reading", "読みが不明な場合に推測せず欠測として扱うこと"),
    ]),
    ("Stroke Counting", "画数計算", [
        ("modern_glyph_count", "新字体画数", "Modern-Glyph Stroke Count", "現代字体の字形にもとづく画数方式"),
        ("traditional_glyph_count", "旧字体画数", "Traditional-Glyph Stroke Count", "旧字体・康熙字典体等を用いる方式"),
        ("radical_adjustment", "部首画数補正", "Radical Stroke Adjustment", "部首の数え方を補正する流派規則"),
        ("variant_character", "異体字", "Variant Character", "異体字をどの標準字へ対応させるかという規則"),
        ("simplified_character", "簡体字", "Simplified Character", "簡体字をそのまま数えるか繁体字へ戻すかという規則"),
        ("kana_stroke_count", "かな画数", "Kana Stroke Count", "かな文字へ画数を割り当てる方式"),
        ("latin_letter_count", "ラテン文字数価", "Latin-Letter Value", "ラテン文字名を別体系で扱う方式"),
        ("middle_dot_handling", "中黒処理", "Middle-Dot Handling", "中黒・ハイフン・空白等を画数へ含めるかという規則"),
        ("one_character_name", "一字名処理", "Single-Character Name Handling", "一字姓・一字名で仮数を加える流派規則"),
        ("stroke_source_version", "画数表版管理", "Stroke-Table Version", "採用画数表と版を記録すること"),
    ]),
    ("Five Grids", "五格", [
        ("heaven_grid", "天格", "Heaven Grid", "姓の画数から算出する五格の一つ"),
        ("person_grid", "人格", "Person Grid", "姓末字と名初字等から算出する五格の一つ"),
        ("earth_grid", "地格", "Earth Grid", "名の画数から算出する五格の一つ"),
        ("outer_grid", "外格", "Outer Grid", "総格・人格等の関係から算出する五格の一つ"),
        ("total_grid", "総格", "Total Grid", "氏名全体の画数から算出する五格の一つ"),
    ]),
    ("Yin Yang and Five Phases", "陰陽五行配当", [
        ("odd_yang", "奇数陽", "Odd-Yang Assignment", "奇数画を陽へ配当する方式"),
        ("even_yin", "偶数陰", "Even-Yin Assignment", "偶数画を陰へ配当する方式"),
        ("yin_yang_sequence", "陰陽配列", "Yin-Yang Sequence", "各文字画数の陰陽並びを読む方式"),
        ("grid_phase", "格の五行", "Grid Five-Phase", "格数末尾等から五行を配当する方式"),
        ("three_talents", "三才配置", "Three-Talents Configuration", "天格・人格・地格の五行関係を読む方式"),
        ("phase_generation", "五行相生", "Phase Generation", "格間の相生関係を扱うこと"),
        ("phase_control", "五行相剋", "Phase Control", "格間の相剋関係を扱うこと"),
        ("same_phase", "五行比和", "Same-Phase Relation", "格間が同じ五行になる関係"),
        ("assignment_variation", "五行配当差", "Assignment Variation", "数と五行の配当表が流派で異なること"),
        ("no_element_essentialism", "五行本質化禁止", "No Element Essentialism", "五行配当を本人の固定的本質にしないこと"),
    ]),
    ("Sound and Reading", "音と読み", [
        ("initial_sound", "語頭音", "Initial Sound", "氏名の最初の音を扱う方式"),
        ("vowel_pattern", "母音配列", "Vowel Pattern", "氏名中の母音の並びを扱う方式"),
        ("consonant_pattern", "子音配列", "Consonant Pattern", "氏名中の子音の並びを扱う方式"),
        ("mora_count", "拍数", "Mora Count", "日本語名のモーラ数を扱う方式"),
        ("voicing", "清濁", "Voicing", "清音・濁音・半濁音の違いを扱う方式"),
        ("long_vowel", "長音", "Long Vowel", "長音を一単位または別単位とする規則"),
        ("contracted_sound", "拗音", "Contracted Sound", "拗音を一拍として扱う規則"),
        ("geminate_sound", "促音", "Geminate Sound", "促音を一拍として扱う規則"),
        ("pitch_accent", "アクセント", "Pitch Accent", "地域差のあるアクセントを普遍化せず扱うこと"),
        ("reading_variation", "読み方差", "Reading Variation", "同じ表記に複数の読みがある場合を併記すること"),
    ]),
    ("Character Meaning", "字義", [
        ("literal_meaning", "字義", "Literal Meaning", "文字の辞書的意味を記録すること"),
        ("name_specific_meaning", "名乗り義", "Name-Specific Meaning", "人名で用いられる意味・読みを記録すること"),
        ("etymology", "字源", "Character Etymology", "文字の成立史を俗説と区別して扱うこと"),
        ("semantic_combination", "字義組合せ", "Semantic Combination", "複数文字の意味を一つに固定せず組み合わせること"),
        ("cultural_association", "文化的連想", "Cultural Association", "文字に付随する歴史・文学・社会的連想"),
        ("generational_character", "通字", "Generational Character", "家族・世代で共有される文字の文脈"),
        ("gendered_convention", "性別化慣習", "Gendered Naming Convention", "名前の性別的慣習を本人属性の断定に使わないこと"),
        ("era_context", "時代文脈", "Era Context", "名前の流行や意味が時代で変化すること"),
        ("regional_context", "地域文脈", "Regional Context", "読み・慣習・連想の地域差"),
        ("meaning_source", "字義出典", "Meaning Source", "字義・字源・名乗りの出典を記録すること"),
    ]),
    ("Systems and Variants", "方式差", [
        ("five_grid_method", "五格法", "Five-Grid Method", "五つの格と数理表を用いる方式"),
        ("eighty_one_numbers", "八十一数理", "Eighty-One Numbers", "1から81等へ吉凶象徴を配当する方式"),
        ("yin_yang_method", "陰陽配列法", "Yin-Yang Sequence Method", "画数の奇偶配列を用いる方式"),
        ("three_talents_method", "三才法", "Three-Talents Method", "天人地の五行関係を用いる方式"),
        ("sound_method", "音霊法", "Sound-Symbolism Method", "氏名の音へ象徴を与える方式"),
        ("meaning_method", "字義法", "Character-Meaning Method", "文字の意味・由来を中心に読む方式"),
        ("birthdate_combination", "生年月日併用法", "Birth-Date Combined Method", "氏名と生年月日を組み合わせる方式"),
        ("old_new_glyph_split", "新旧字体方式差", "Old-New Glyph Split", "新字体・旧字体で結果が異なること"),
        ("regional_method", "地域方式", "Regional Method", "日本・中国・韓国等の姓名占術を同一視しないこと"),
        ("method_non_equivalence", "方式非等価性", "Method Non-Equivalence", "異なる方式の結果を合算して単一評価にしないこと"),
    ]),
    ("Workflow", "処理手順", [
        ("consent", "氏名利用同意", "Name-Use Consent", "氏名を占術処理へ使用する同意を得ること"),
        ("purpose", "利用目的", "Use Purpose", "内省・創作等の利用目的を明示すること"),
        ("select_name_version", "氏名版選択", "Select Name Version", "出生名・現在名・活動名等を選ぶこと"),
        ("select_script", "文字体系選択", "Select Script", "漢字・かな・ラテン文字等を選ぶこと"),
        ("select_dictionary", "画数字典選択", "Select Stroke Dictionary", "採用する字体・画数表を選ぶこと"),
        ("normalize_characters", "文字正規化", "Character Normalization", "異体字等の変換を記録すること"),
        ("count_strokes", "画数算出", "Stroke Counting", "各文字の画数と根拠を表示すること"),
        ("calculate_grids", "格算出", "Grid Calculation", "採用方式で五格等を算出すること"),
        ("apply_number_table", "数理表適用", "Number-Table Application", "数値を採用流派の表へ照合すること"),
        ("calculate_phase_relations", "五行関係算出", "Phase-Relation Calculation", "格の五行と相互関係を算出すること"),
        ("analyze_reading", "読み分析", "Reading Analysis", "音・拍・読みを採用方式で扱うこと"),
        ("analyze_meaning", "字義分析", "Meaning Analysis", "文字の意味・由来・文化文脈を整理すること"),
        ("compare_methods", "方式比較", "Method Comparison", "異なる方式の結果を別々に表示すること"),
        ("show_uncertainty", "不確実性表示", "Uncertainty Display", "字体・読み・画数・流派差を表示すること"),
        ("user_review", "本人確認", "User Review", "本人が正しい表記・読み・意味を確認し修正できること"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("no_name_quality_rank", "名前優劣禁止", "No Name-Quality Ranking", "名前や命名者の価値を吉凶で序列化しないこと"),
        ("no_personality_fixing", "性格固定禁止", "No Personality Fixing", "氏名から固定的人格・能力を断定しないこと"),
        ("no_discrimination", "名前差別禁止", "No Name Discrimination", "氏名から民族・国籍・宗教・階級等を推定・差別しないこと"),
        ("no_hiring_use", "採用利用禁止", "No Hiring Use", "応募者や従業員の判断へ姓名判断を使用しないこと"),
        ("no_child_pressure", "命名圧力回避", "Avoid Naming Pressure", "子どもの将来を画数で保証・脅迫しないこと"),
        ("no_fatalism", "凶名宿命論回避", "Avoid Name Fatalism", "凶名等を不可避の不幸として表示しないこと"),
        ("privacy_minimization", "氏名情報最小化", "Name-Data Minimization", "氏名・旧姓・生年月日の収集と保持を最小化すること"),
        ("deletion_control", "削除管理", "Deletion Control", "入力名と派生結果を利用者が削除できること"),
        ("method_disclosure", "方式開示", "Method Disclosure", "画数表・字体・格計算・流派を表示すること"),
        ("reflective_use", "内省・創作用途", "Reflective and Creative Use", "結果を任意の内省・創作・娯楽として示すこと"),
    ]),
]


FENG_SHUI_SECTIONS = [
    ("Foundations", "基礎", [
        ("feng_shui", "風水", "Feng Shui", "地形・方位・建物・時間を扱う中国由来の伝統的環境解釈体系"),
        ("kanyu", "堪輿", "Kanyu", "天地と場所を扱う風水の歴史的呼称"),
        ("qi_flow", "気の流れ", "Qi Flow", "場所の配置と動きを説明する伝統的象徴概念"),
        ("yin_yang_context", "陰陽環境", "Yin-Yang Environmental Context", "明暗・動静・開閉等を陰陽で分類すること"),
        ("five_phase_context", "五行環境", "Five-Phase Environmental Context", "方位・形・色・素材等を五行へ対応づけること"),
        ("form_school", "形勢派", "Form School", "山水や地形・形状を重視する風水系統"),
        ("compass_school", "理気派", "Compass School", "羅盤・方位・時間計算を重視する風水系統"),
        ("living_site", "陽宅", "Yang Dwelling", "住居・都市等の生者の環境を扱う領域"),
        ("burial_site", "陰宅", "Yin Dwelling", "墓地等を扱う歴史的風水領域"),
        ("school_declaration", "流派宣言", "School Declaration", "形勢・八宅・玄空等の採用方式を明示すること"),
    ]),
    ("Form School", "形勢", [
        ("mountain_form", "山形", "Mountain Form", "周囲の山地形状を読む伝統的概念"),
        ("water_form", "水勢", "Water Form", "河川・湖沼・水路の形と流れを読む概念"),
        ("dragon_vein", "龍脈", "Dragon Vein", "山脈の連なりを気の経路として捉える象徴"),
        ("lair", "穴", "Lair", "地形上の気が集まるとされる地点概念"),
        ("sand", "砂", "Sand Forms", "中心地点を囲む丘陵等を扱う概念"),
        ("facing_water", "向水", "Facing Water", "正面側の水との位置関係"),
        ("back_support", "背山", "Back Support", "背後の地形や建物による支えの象徴"),
        ("left_dragon", "青龍方", "Azure Dragon Side", "中心から見た左側の形勢分類"),
        ("right_tiger", "白虎方", "White Tiger Side", "中心から見た右側の形勢分類"),
        ("front_bird", "朱雀方", "Vermilion Bird Side", "中心から見た前方の形勢分類"),
        ("rear_tortoise", "玄武方", "Black Tortoise Side", "中心から見た後方の形勢分類"),
        ("bright_hall", "明堂", "Bright Hall", "建物・地点前方の開けた空間概念"),
        ("poison_arrow", "形煞", "Form Sha", "鋭角・直線等を不調和として読む伝統的形状概念"),
        ("site_enclosure", "環抱", "Site Enclosure", "周囲が包むような地形・配置"),
        ("form_context", "形勢総合", "Form Context", "一つの形だけでなく周辺環境全体を扱うこと"),
    ]),
    ("Compass School", "理気", [
        ("luopan", "羅盤", "Luopan", "方位と複数の伝統的尺度を同心円状に示す風水羅盤"),
        ("sitting_direction", "坐", "Sitting Direction", "建物の背面側として定義する方位"),
        ("facing_direction", "向", "Facing Direction", "建物の正面側として定義する方位"),
        ("twenty_four_mountains", "二十四山", "Twenty-Four Mountains", "全方位を二十四区画へ分ける方式"),
        ("heaven_plate", "天盤", "Heaven Plate", "羅盤上の天盤系方位層"),
        ("earth_plate", "地盤", "Earth Plate", "羅盤上の地盤系方位層"),
        ("human_plate", "人盤", "Human Plate", "羅盤上の人盤系方位層"),
        ("magnetic_bearing", "磁気方位", "Magnetic Bearing", "磁北を基準に測る方位角"),
        ("true_north", "真北", "True North", "地理上の北を基準とする方位"),
        ("declination", "磁気偏角", "Magnetic Declination", "磁北と真北の角度差"),
        ("measurement_point", "測定地点", "Measurement Point", "方位を測定する建物内外の基準位置"),
        ("building_facing", "建物向判定", "Building Facing", "入口・採光・道路等から向きを定める流派規則"),
        ("compass_interference", "磁気干渉", "Compass Interference", "金属・電気設備等が羅盤測定へ与える影響"),
        ("bearing_uncertainty", "方位測定不確実性", "Bearing Uncertainty", "測定誤差と境界付近を表示すること"),
        ("compass_school_context", "理気総合", "Compass-School Context", "方位・時間・流派の複数規則を分けて扱うこと"),
    ]),
    ("Eight Directions", "八方位", named([
        ("north", "北", "North"), ("northeast", "北東", "Northeast"),
        ("east", "東", "East"), ("southeast", "南東", "Southeast"),
        ("south", "南", "South"), ("southwest", "南西", "Southwest"),
        ("west", "西", "West"), ("northwest", "北西", "Northwest"),
    ], "風水の八方位{name}に割り当てられる卦・五行・象徴対応")),
    ("Eight Trigrams", "八卦", named([
        ("kan", "坎", "Kan"), ("gen", "艮", "Gen"), ("zhen", "震", "Zhen"),
        ("xun", "巽", "Xun"), ("li", "離", "Li"), ("kun", "坤", "Kun"),
        ("dui", "兌", "Dui"), ("qian", "乾", "Qian"),
    ], "後天八卦の{name}に割り当てられる方位・五行・象徴")),
    ("Five-Phase Relations", "五行関係", [
        ("wood_environment", "木の環境象徴", "Wood Environment", "成長・植物・東等へ対応づける環境象徴"),
        ("fire_environment", "火の環境象徴", "Fire Environment", "光・熱・南等へ対応づける環境象徴"),
        ("earth_environment", "土の環境象徴", "Earth Environment", "地面・中央・安定等へ対応づける環境象徴"),
        ("metal_environment", "金の環境象徴", "Metal Environment", "金属・円形・西等へ対応づける環境象徴"),
        ("water_environment", "水の環境象徴", "Water Environment", "水流・曲線・北等へ対応づける環境象徴"),
        ("generating_relation", "環境相生", "Environmental Generation", "空間要素間の相生関係"),
        ("controlling_relation", "環境相剋", "Environmental Control", "空間要素間の相剋関係"),
        ("phase_balance", "五行配分", "Phase Balance", "空間内の五行象徴を配分として整理すること"),
        ("material_symbolism", "素材象徴", "Material Symbolism", "素材を五行へ対応づける伝統的分類"),
        ("color_symbolism", "色彩象徴", "Color Symbolism", "色を五行へ対応づける伝統的分類"),
    ]),
    ("Eight Mansions", "八宅", [
        ("east_group", "東四命・東四宅", "East Group", "八卦を東系グループへ分類する方式"),
        ("west_group", "西四命・西四宅", "West Group", "八卦を西系グループへ分類する方式"),
        ("life_gua", "命卦", "Life Gua", "生年等から求める八宅上の個人卦"),
        ("house_gua", "宅卦", "House Gua", "建物の坐向から求める八宅分類"),
        ("sheng_qi", "生気", "Sheng Qi", "八宅で用いる伝統的方位分類の一つ"),
        ("tian_yi", "天医", "Tian Yi", "八宅で用いる伝統的方位分類の一つ"),
        ("yan_nian", "延年", "Yan Nian", "八宅で用いる伝統的方位分類の一つ"),
        ("fu_wei", "伏位", "Fu Wei", "八宅で用いる伝統的方位分類の一つ"),
        ("four_challenging_sectors", "四凶方分類", "Four Challenging Sectors", "八宅で用いる四つの注意方位分類"),
        ("eight_mansions_variation", "八宅流派差", "Eight-Mansions Variation", "命卦・宅卦・方位割当の流派差を表示すること"),
    ]),
    ("Flying Stars", "玄空飛星", [
        ("flying_star_grid", "飛星盤", "Flying-Star Grid", "九宮へ星数を配置する玄空飛星の盤"),
        ("period", "運", "Period", "建物時期を一定期間へ分類する方式"),
        ("base_star", "運星", "Base Star", "各宮の基礎となる期間星"),
        ("mountain_star", "山星", "Mountain Star", "坐側の計算から配置する星"),
        ("water_star", "向星", "Water Star", "向側の計算から配置する星"),
        ("annual_star", "年飛星", "Annual Flying Star", "年ごとに移る九星配置"),
        ("monthly_star", "月飛星", "Monthly Flying Star", "月ごとに移る九星配置"),
        ("forward_reverse_flight", "順飛逆飛", "Forward-Reverse Flight", "陰陽等に応じて九星を巡らせる方向"),
        ("building_period_change", "建物運変更", "Building-Period Change", "改築等で建物の運を変更するとみなす流派規則"),
        ("flying_star_version", "飛星方式版管理", "Flying-Star Method Version", "運区分・起星・替星等の採用規則を保持すること"),
    ]),
    ("Built Environment", "建築環境", [
        ("entrance_context", "入口文脈", "Entrance Context", "入口の位置・動線・採光を環境として整理すること"),
        ("room_function", "室用途", "Room Function", "寝室・仕事場等の用途と配置を扱うこと"),
        ("circulation", "動線", "Circulation", "人の移動経路と障害を整理すること"),
        ("light_ventilation", "採光換気", "Light and Ventilation", "光・換気・湿気等の実際の環境条件を記録すること"),
    ]),
    ("Safety and Limits", "安全と限界", [
        ("building_safety_priority", "建築安全優先", "Building Safety Priority", "耐震・防火・避難・法令を風水より優先すること"),
        ("environmental_health_priority", "環境衛生優先", "Environmental Health Priority", "換気・カビ・有害物質等を専門基準で判断すること"),
        ("no_disaster_prediction", "災害予測禁止", "No Disaster Prediction", "地形・方位から災害を確定予測しないこと"),
        ("no_health_claim", "健康効果保証禁止", "No Health Claim", "配置や色で治療・健康効果を保証しないこと"),
        ("no_property_value_claim", "資産価値保証禁止", "No Property-Value Claim", "風水で不動産価値や投資成果を保証しないこと"),
        ("no_resident_inference", "居住者推定禁止", "No Resident Inference", "住環境から居住者の性格・民族・宗教等を推定しないこと"),
        ("school_variation", "流派差", "School Variation", "形勢・八宅・飛星等の結果を混同しないこと"),
        ("location_privacy", "住所情報保護", "Location Privacy", "住所・間取り・方位データの収集と保持を最小化すること"),
        ("professional_boundary", "専門家境界", "Professional Boundary", "建築・構造・医療・環境の専門判断を代替しないこと"),
        ("reflective_design_use", "内省的設計用途", "Reflective Design Use", "結果を任意の空間対話・文化的デザイン参考として示すこと"),
    ]),
]


CONFIGS = [
    ({"prefix": "JYO", "knowledge_type": "indian_astrology", "category": "Indian Astrology", "category_tag": "CAT:インド占星術", "label": "インド占星術", "tradition": "ジョーティシャ・インド占星術", "source_type": "生年月日・出生時刻・出生地・天体暦", "required_inputs": ["生年月日", "出生時刻", "出生地", "時間帯", "アヤナーンシャ", "採用流派"], "calculation_basis": "恒星黄道上のグラハ・ラーシ・バーヴァ・ナクシャトラを採用方式で計算する", "provenance": "インドのジョーティシャ文献・暦算・出生占星術の諸流派", "output_dir": "vol35_indian_astrology/indian_astrology_001_100", "index_filename": "indian_astrology_001_100_index.yml", "master_filename": "vol35_indian_astrology_001_100.json"}, JYOTISHA_SECTIONS),
    ({"prefix": "ZWD", "knowledge_type": "zi_wei_dou_shu", "category": "Zi Wei Dou Shu", "category_tag": "CAT:紫微斗数", "label": "紫微斗数", "tradition": "紫微斗数", "source_type": "生年月日・出生時刻・太陰太陽暦・干支", "required_inputs": ["生年月日", "出生時刻", "出生地と時間帯", "暦変換規則", "流派星表"], "calculation_basis": "出生月日・時支・干支等から十二宮と星曜を流派表に従い配置する", "provenance": "明代以後に確認される紫微斗数文献と中国語圏の諸流派", "output_dir": "vol36_zi_wei_dou_shu/zi_wei_dou_shu_001_100", "index_filename": "zi_wei_dou_shu_001_100_index.yml", "master_filename": "vol36_zi_wei_dou_shu_001_100.json"}, ZWD_SECTIONS),
    ({"prefix": "NSK", "knowledge_type": "nine_star_ki", "category": "Nine Star Ki", "category_tag": "CAT:九星気学", "label": "九星気学", "tradition": "九星気学・九星術", "source_type": "生年月日・対象日時・地点・方位", "required_inputs": ["生年月日", "対象日時", "出発地", "目的地", "方位方式", "暦表"], "calculation_basis": "九星・九宮・五行・節気にもとづき年盤・月盤・日盤等を計算する", "provenance": "中国の九星・九宮・方位術と日本で体系化された気学諸流派", "output_dir": "vol37_nine_star_ki/nine_star_ki_001_100", "index_filename": "nine_star_ki_001_100_index.yml", "master_filename": "vol37_nine_star_ki_001_100.json"}, NINE_STAR_SECTIONS),
    ({"prefix": "SUK", "knowledge_type": "sukuyo", "category": "Sukuyo", "category_tag": "CAT:宿曜", "label": "宿曜", "tradition": "宿曜・宿曜道", "source_type": "生年月日・暦・月宿・七曜", "required_inputs": ["生年月日", "使用暦", "二十七宿または二十八宿方式", "基準日", "流派"], "calculation_basis": "採用暦と基準配列から本命宿・日運宿・宿間関係等を求める", "provenance": "インド月宿・漢訳宿曜経・日本の密教占星と宿曜道の歴史", "output_dir": "vol38_sukuyo/sukuyo_001_100", "index_filename": "sukuyo_001_100_index.yml", "master_filename": "vol38_sukuyo_001_100.json"}, SUKUYO_SECTIONS),
    ({"prefix": "NUM", "knowledge_type": "numerology", "category": "Numerology", "category_tag": "CAT:数秘術", "label": "数秘術", "tradition": "数秘術・数象徴", "source_type": "生年月日・氏名・採用文字数値表", "required_inputs": ["生年月日", "使用する氏名版", "文字体系", "数値配当方式", "還元規則"], "calculation_basis": "日付数字または文字数値を採用方式で合計・還元し各数を得る", "provenance": "古代から近現代までの数象徴・文字数価・西洋数秘術の諸方式", "output_dir": "vol39_numerology/numerology_001_100", "index_filename": "numerology_001_100_index.yml", "master_filename": "vol39_numerology_001_100.json"}, NUMEROLOGY_SECTIONS),
    ({"prefix": "NAM", "knowledge_type": "name_divination", "category": "Name Divination", "category_tag": "CAT:姓名判断", "label": "姓名判断", "tradition": "日本の姓名判断・姓名学", "source_type": "氏名表記・読み・字体・画数表", "required_inputs": ["本人同意", "対象氏名版", "正確な表記", "読み", "採用字典", "流派"], "calculation_basis": "採用字体の画数・五格・陰陽五行・音・字義を方式別に算出する", "provenance": "日本で発展した近現代の姓名判断・五格法・音義法の諸流派", "output_dir": "vol40_name_divination/name_divination_001_100", "index_filename": "name_divination_001_100_index.yml", "master_filename": "vol40_name_divination_001_100.json"}, NAME_SECTIONS),
    ({"prefix": "FSH", "knowledge_type": "feng_shui", "category": "Feng Shui", "category_tag": "CAT:風水", "label": "風水", "tradition": "中国風水・堪輿", "source_type": "地形・建物・間取り・方位・時間・流派", "required_inputs": ["対象地点", "建物用途", "方位測定", "周辺環境", "建築時期", "採用流派"], "calculation_basis": "形勢・羅盤方位・八卦・五行・時間盤を流派別に整理する", "provenance": "中国の堪輿・形勢派・理気派と東アジアに展開した風水諸流派", "output_dir": "vol41_feng_shui/feng_shui_001_100", "index_filename": "feng_shui_001_100_index.yml", "master_filename": "vol41_feng_shui_001_100.json"}, FENG_SHUI_SECTIONS),
]


def main():
    for config, sections in CONFIGS:
        build_pack(config, sections)


if __name__ == "__main__":
    main()
